"""Auto migration

Revision ID: 2f81ffbfa86a
Revises: cb2e5d8bf6ec
Create Date: 2025-07-22 21:57:01.183276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f81ffbfa86a'
down_revision = 'cb2e5d8bf6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
