"""Realtion column in user database made non compulsory

Revision ID: cb2e5d8bf6ec
Revises: c0fdf2705e80
Create Date: 2025-06-29 22:13:40.409050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2e5d8bf6ec'
down_revision = 'c0fdf2705e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('relation')

    # ### end Alembic commands ###
